### PR TITLE
Add types of emits

### PR DESCRIPTION
**Pull request by kingyue737**
## Description

As some upstream type bugs https://github.com/vuejs/language-tools/issues/1855 have been resolved, now we can have intellisense of events in SFC templates.

image

image

Not fully tested as I only use a small subset of all vuetify component events in my projects. Help wanted XD

### Ensure that your pull request has followed all the steps below:
- [ ] Code compilation
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by ascott18** [comment]
Awesome - thank you!

**Comment by johuhype** [comment]
Could you please have a look at v-calendar. At least the events for @change, @click:event, @click:date, @click:more are not getting processed correctly, altough they seem to be defined correctly on the documentation page.

e.g.
Type '(range: { start: CalendarTimestamp; end: CalendarTimestamp; }) => void' is not assignable to type '(...args: unknown[]) => void'.
Types of parameters 'range' and 'args' are incompatible.ts(2322)
(property) 'change': ((...args: unknown[]) => void) | undefined

**Comment by kingyue737** [comment]
@johuhype sorry I wasn't notified as I unsubscribed this PR after closed, I will check this issue this week

**Comment by kingyue737** [comment]
seems to be an upstream bug https://github.com/vuejs/language-tools/issues/3719

**Pull request merged**
